/** Glossary of key terms — sits between the Conclusion and the Bibliography. */

const GLOSSARY = [
  { t: 'h1', text: 'Glossary of Key Terms' },
  {
    t: 'p', italicAll: true, text:
      'Every technical term used in this report is defined below, in the sense in which the ' +
      'report uses it. Terms are listed alphabetically.',
  },
  {
    t: 'table',
    widths: [2500, 6526],
    colAlign: ['left', 'left'],
    head: ['Term', 'Meaning as used in this report'],
    rows: [
      ['Average ticket size',
        'The average value of a single transaction, obtained by dividing total transaction value by total transaction volume. Derived by the author in Table 2; not published by any source.'],
      ['Base year revision',
        'A periodic updating of the reference year used to compute national income. India moved from a 2011-12 base to a 2022-23 base during the study period, so GDP figures either side of the change are not perfectly comparable.'],
      ['CAGR',
        'Compound Annual Growth Rate — the constant yearly rate at which a quantity would have to grow to move from its starting value to its ending value over the period.'],
      ['Cambridge cash-balance approach',
        'The formulation M = k × P × Y, which views money demand as the fraction of income people choose to hold as money. Velocity is the reciprocal of that fraction, so V = 1 ÷ k.'],
      ['Currency in Circulation (CIC)',
        'The total value of banknotes and coins in the hands of the public and in bank tills. India’s CIC-to-GDP ratio is high by international standards, and reducing it is a stated aim of RBI policy.'],
      ['Demonetisation',
        'The withdrawal of legal tender status from ₹500 and ₹1,000 banknotes on 9 November 2016, affecting ₹15.4 trillion, or 86.9 per cent of the value of notes then in circulation.'],
      ['Digital public infrastructure',
        'Open, interoperable digital systems that support society-wide public and private services. The Bank for International Settlements treats fast payment systems such as UPI as the archetype.'],
      ['Equation of exchange',
        'Fisher’s identity M × V = P × T, relating the money stock and its velocity to the price level and the volume of transactions. It is true by construction rather than by assumption.'],
      ['Fast payment system',
        'A retail payment system settling in or near real time, available continuously. UPI is the largest such system in the world by transaction volume.'],
      ['Financial inclusion',
        'Access to useful and affordable financial services. Measured in India by the RBI’s Financial Inclusion Index across three sub-indices: access, usage and quality.'],
      ['Formalisation',
        'The movement of economic activity from the unrecorded to the recorded economy. A digital payment leaves a record; records accumulate into a credit history.'],
      ['Income velocity',
        'The number of times a unit of money is used to buy newly produced output, computed as nominal national income divided by the money stock. The conservative measure of velocity, and the one that moves slowly.'],
      ['Interoperability',
        'The property that a user of one application or bank can transact with a user of any other. This is the design feature the IMF identifies as the source of UPI’s adoption.'],
      ['k (cash-balance ratio)',
        'The fraction of nominal income that people choose to hold as money. A fall in k is arithmetically the same statement as a rise in velocity.'],
      ['Merchant Discount Rate (MDR)',
        'The fee a merchant pays on each digital transaction. It is zero for UPI transactions up to ₹2,000 for small merchants, with the Government paying an incentive of 0.15 per cent of transaction value in its place.'],
      ['Natural experiment',
        'A real-world event that changes conditions sharply and without the researcher’s intervention, allowing before-and-after comparison. Demonetisation is treated as one in Data Set 5.'],
      ['Nominal GDP',
        'The value of national output measured at current prices, so it rises with both output and inflation. Used as the denominator in Table 4.'],
      ['NPCI',
        'The National Payments Corporation of India — the not-for-profit umbrella organisation that built and operates UPI, sets its standards and settles positions between member banks.'],
      ['P2M and P2P',
        'Person-to-merchant and person-to-person transactions. P2M now forms 63 per cent of UPI volume, and 86 per cent of P2M payments are below ₹500.'],
      ['PIDF',
        'The Payments Infrastructure Development Fund, which subsidises the deployment of acceptance infrastructure — QR codes and terminals — in tier-3 to tier-6 centres.'],
      ['RBI Digital Payments Index',
        'A composite RBI index measuring the extent of payment digitalisation, with March 2018 set equal to 100. It stood at 493.22 in March 2025.'],
      ['Real-time settlement',
        'Settlement of a payment within seconds of it being initiated, as against batch processing at fixed intervals.'],
      ['Secondary data',
        'Data collected and published by someone other than the researcher. This entire study rests on secondary data, which is stated as its first limitation.'],
      ['Structural break',
        'A point at which the statistical relationship between variables changes, usually because of a shock or a policy change. COVID-19 is identified as one in the literature reviewed in Section 3.6.'],
      ['Transactions velocity',
        'The number of times a unit of money is used in any payment, including transfers that are not purchases of output. Payment systems act on this measure directly, and it can move much faster than income velocity.'],
      ['UPI',
        'The Unified Payments Interface — a common standard, launched in 2016, allowing any bank account to be addressed by any application through a single virtual payment address.'],
      ['Velocity of money',
        'The average number of times one unit of currency is used to purchase goods and services in a given period. A behavioural property, not a physical one.'],
      ['Virtual Payment Address',
        'A short identifier that stands in for a bank account number and branch code when making a UPI payment.'],
    ],
    note:
      'A note on one ambiguity: the abbreviation DPI is used in two senses in the payments ' +
      'literature — "digital public infrastructure" and the RBI’s "Digital Payments Index". ' +
      'This report spells both out in full wherever they appear.',
  },
  { t: 'pb' },
];

module.exports = { GLOSSARY };
