/** Glossary of key terms — sits between the Conclusion and the Bibliography. */

const GLOSSARY = [
  { t: 'h1', text: 'Glossary of Key Terms' },
  {
    t: 'p', italicAll: true, text:
      'Every technical term used in this report is explained below, in the sense in which I use ' +
      'it. The terms are in alphabetical order.',
  },
  {
    t: 'table',
    widths: [2500, 6526],
    colAlign: ['left', 'left'],
    head: ['Term', 'What it means in this report'],
    rows: [
      ['Average ticket size',
        'The average value of one payment. You get it by dividing total value by total volume. I worked this out myself in Table 2. It is not published by any source.'],
      ['Base year revision',
        'A change in the reference year used to measure national income. India moved from a 2011-12 base to a 2022-23 base during my study period. So GDP figures from before and after the change do not match perfectly.'],
      ['CAGR',
        'Compound Annual Growth Rate. It is the steady yearly rate that would take a number from its starting value to its final value over the period.'],
      ['Cambridge cash-balance approach',
        'The formula M = k × P × Y. It treats the demand for money as the share of income people choose to hold as money. Velocity is one divided by k.'],
      ['Currency in Circulation (CIC)',
        'The total value of notes and coins held by the public and in bank tills. India’s CIC compared with GDP is high by world standards, and the RBI wants to bring it down.'],
      ['Demonetisation',
        'The withdrawal of legal tender status from ₹500 and ₹1,000 notes on 9 November 2016. The notes were worth ₹15.4 trillion, which was 86.9 per cent of the value of all notes then in circulation.'],
      ['Digital public infrastructure',
        'Open digital systems that anyone can join and that serve the whole country. The Bank for International Settlements treats fast payment systems like UPI as the clearest example.'],
      ['Equation of exchange',
        'Fisher’s equation M × V = P × T. It links the money stock and its velocity to the price level and the number of transactions. It is true by definition, not by assumption.'],
      ['Fast payment system',
        'A retail payment system that settles instantly or almost instantly, and runs all the time. UPI is the largest one in the world by number of payments.'],
      ['Financial inclusion',
        'Being able to use financial services that are useful and affordable. In India it is measured by the RBI’s Financial Inclusion Index, which has three parts: access, usage and quality.'],
      ['Formalisation',
        'Economic activity moving from unrecorded to recorded. A digital payment leaves a record, and records build up into a credit history.'],
      ['Income velocity',
        'How many times a rupee is used to buy newly produced goods and services. You find it by dividing national income by the money stock. It is the safer measure of velocity, and it moves slowly.'],
      ['Interoperability',
        'Being able to pay a user of any other app or bank, not only one on the same service. The IMF says this is the design feature that made UPI spread.'],
      ['k (cash-balance ratio)',
        'The share of income people choose to keep as money. A fall in k means exactly the same thing as a rise in velocity.'],
      ['Merchant Discount Rate (MDR)',
        'The fee a shopkeeper pays on each digital payment. For UPI it is zero on small-merchant payments up to ₹2,000. The Government pays 0.15 per cent of the value instead.'],
      ['Natural experiment',
        'A real event that changes conditions sharply, without a researcher planning it. This lets us compare before and after. I treat demonetisation as one in Data Set 5.'],
      ['Nominal GDP',
        'The value of what the country produces, measured at current prices. It rises with both output and inflation. I use it as the bottom of the ratio in Table 4.'],
      ['NPCI',
        'The National Payments Corporation of India. It is the not-for-profit body that built and runs UPI, writes its rules, and settles money between member banks.'],
      ['P2M and P2P',
        'Person-to-merchant and person-to-person payments. P2M is now 63 per cent of UPI volume, and 86 per cent of P2M payments are below ₹500.'],
      ['PIDF',
        'The Payments Infrastructure Development Fund. It pays part of the cost of putting QR codes and card machines into tier-3 to tier-6 towns.'],
      ['RBI Digital Payments Index',
        'An RBI index that measures how far payments have gone digital. March 2018 is set at 100. It stood at 493.22 in March 2025.'],
      ['Real-time settlement',
        'A payment that is completed within seconds of being sent, instead of being processed in batches at fixed times.'],
      ['Secondary data',
        'Data collected and published by someone other than the researcher. My whole study uses secondary data, and I list this as its first limitation.'],
      ['Structural break',
        'A point where the relationship between two things changes, usually because of a shock or a new policy. COVID-19 is treated as one in the research in Section 3.6.'],
      ['Transactions velocity',
        'How many times a rupee is used in any payment at all. This includes transfers that do not buy anything new. Payment systems affect this measure directly, and it can move much faster than income velocity.'],
      ['UPI',
        'The Unified Payments Interface. It is a common set of rules, launched in 2016, that lets any bank account be paid from any app using a single short address.'],
      ['Velocity of money',
        'The average number of times one rupee is used to buy goods and services in a given period. It describes behaviour, not a physical quality of money.'],
      ['Virtual Payment Address',
        'A short name that stands in for a bank account number and branch code when making a UPI payment.'],
    ],
    note:
      'A note on one confusing abbreviation. DPI is used in two different ways in writing about ' +
      'payments. It can mean "digital public infrastructure" or the RBI’s "Digital Payments ' +
      'Index". I have written both out in full everywhere they appear.',
  },
  { t: 'pb' },
];

module.exports = { GLOSSARY };
